"""add donation model and relationships

Revision ID: 69878ec44fc8
Revises: ad5acb761736
Create Date: 2025-10-25 15:49:08.296180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69878ec44fc8'
down_revision = 'ad5acb761736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('donation_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_donations_donor_id_users')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_donations_report_id_reports')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    # ### end Alembic commands ###
