"""add donation model and relationships

Revision ID: 7ec8ac22c392
Revises: 69878ec44fc8
Create Date: 2025-10-25 16:27:40.794680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec8ac22c392'
down_revision = '69878ec44fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('donor_email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('donation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('message')
        batch_op.drop_column('donation_date')
        batch_op.drop_column('donor_email')
        batch_op.drop_column('donor_name')

    # ### end Alembic commands ###
