"""Add AI confidence and explanation fields to Report model

Revision ID: 937283d60ea6
Revises: d7823fd8a205
Create Date: 2025-10-28 14:15:03.681545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937283d60ea6'
down_revision = 'd7823fd8a205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type_explanation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('severity_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('severity_explanation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('severity_explanation')
        batch_op.drop_column('severity_confidence')
        batch_op.drop_column('type_explanation')
        batch_op.drop_column('type_confidence')

    # ### end Alembic commands ###
