"""update donation model fields

Revision ID: 9922b07a9c57
Revises: 7ec8ac22c392
Create Date: 2025-10-25 20:25:19.507128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9922b07a9c57'
down_revision = '7ec8ac22c392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('amount_number', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_donations_donor_id_users'), type_='foreignkey')
        batch_op.drop_column('donation_date')
        batch_op.drop_column('donor_id')
        batch_op.drop_column('status')
        batch_op.drop_column('donation_type')
        batch_op.drop_column('donor_name')
        batch_op.drop_column('donor_email')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('donor_email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('donor_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('donation_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('donor_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('donation_date', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_donations_donor_id_users'), 'users', ['donor_id'], ['id'])
        batch_op.alter_column('amount',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount_number')
        batch_op.drop_column('type')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
